import {
  Tag,
  Utensils,
  Car,
  Home,
  Zap,
  GraduationCap,
  Tv,
  Heart,
  Shirt,
  Plane,
  Gift,
  Briefcase,
  TrendingUp,
  DollarSign,
  ShoppingBag,
  Ambulance,
} from "lucide-react";

export const iconLookup: Record<string, React.ComponentType<{ className?: string }>> = {
  tag: Tag,
  utensils: Utensils,
  car: Car,
  home: Home,
  zap: Zap,
  "graduation-cap": GraduationCap,
  tv: Tv,
  heart: Heart,
  shirt: Shirt,
  plane: Plane,
  gift: Gift,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "dollar-sign": DollarSign,
  "shopping-bag": ShoppingBag,
  ambulance: Ambulance,
};
